apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list-manager
  labels:
    app: todo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: api
        image: todo-list-manager:latest
        imagePullPolicy: Never # Minikube içindeki image'i kullanmak için
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        envFrom:
        - configMapRef:
            name: todo-config
