apiVersion: v1
kind: Service
metadata:
  name: todo-list-manager-service
spec:
  type: NodePort
  selector:
    app: todo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30080
