apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-list-manager.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "todo-list-manager.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "todo-list-manager.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "todo-list-manager.name" . }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "todo-list-manager.fullname" . }}-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
