replicaCount: 2

image:
  repository: todo-list-manager
  tag: latest
  pullPolicy: Never

service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: 30080

env:
  DATABASE_URL: sqlite:///./todos.db
  S3_ENDPOINT: http://localstack:4566
  OTEL_ENABLED: "false"
  OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4317

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
